# Generated by Django 4.0.4 on 2022-05-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='created',
            new_name='created_at',
        ),
    ]
