# Generated by Django 4.0.4 on 2022-05-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLibrarian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
