# Generated by Django 4.0.4 on 2022-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentLibrarian', '0002_rename_create_by_librarian_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
